---

- name: Install Logstash using repository
  block:

    - name: Logstash Yum Repository (RedHat)
      copy:
        dest: "/etc/yum.repos.d/logstash-{{ logstash_version }}.repo"
        content: "{{ logstash_yum_config }}"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Logstash packages (RedHat)
      yum:
        state: present
        name: "{{ logstash_package }}"
        update_cache: true

  when: logstash_use_repo

- name: Install Logstash using download
  block:

    - name: Download Logstash RPM
      get_url:
        url: "{{ logstash_package_url }}"
        dest: "/var/cache/yum/{{ ansible_architecture }}/{{ logstash_package_name }}-{{ logstash_version }}.rpm"

    - name: Install Logstash from RPM
      yum:
        state: present
        name: "/var/cache/yum/{{ ansible_architecture }}/{{ logstash_package_name }}-{{ logstash_version }}.rpm"
      notify: logstash restart

  when: not logstash_use_repo

# vi:ts=2:sw=2:et:ft=yaml
