---

- name: Install Logstash using repository
  block:

    - name: Add Logstash GPG key.
      rpm_key:
        key: "{{ logstash_gpg_key }}"
        state: present

    - name: Logstash Yum Repository (RedHat)
      template:
        src: logstash.repo.j2
        dest: /etc/yum.repos.d/logstash.repo
        owner: root
        group: root
        mode: 0644

    - name: Logstash packages (RedHat)
      yum:
        state: "{{ (logstash_upgrade) | ternary('latest', 'present') }}"
        name: "{{ logstash_package }}"
        update_cache: true

  when: logstash_use_repo

- name: Install Logstash using download
  block:

    - name: Download Logstash RPM
      get_url:
        url: "{{ logstash_package_url }}"
        dest: "/var/cache/yum/{{ ansible_architecture }}/{{ logstash_package_name }}-{{ logstash_version }}.rpm"

    - name: Install Logstash from RPM
      yum:
        state: present
        name: "/var/cache/yum/{{ ansible_architecture }}/{{ logstash_package_name }}-{{ logstash_version }}.rpm"
      notify: logstash restart

  when: not logstash_use_repo

# Workaround for known logstash issue 'Missing systemd scripts in 6.2.4 #9403'
- name: Check status of systemd logstash.service
  stat:
    path: /etc/systemd/system/logstash.service
  register: logstash_service_status

- name: Create logstash service if it doesn't already exists
  shell: "{{ logstash_install_dir }}/bin/system-install {{ logstash_conf_prefix }}/startup.options systemd"
  when: logstash_service_status.stat.exists == false

# vi:ts=2:sw=2:et:ft=yaml
