---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- import_tasks: install.yml
  tags: logstash_install

- import_tasks: config.yml
  tags: logstash_config

- import_tasks: plugins.yml
  tags: logstash_plugins

- name: Logstash start at boot time
  service:
    name=logstash
    enabled=yes

# vi:ts=2:sw=2:et:ft=yaml
